name: golangci-lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          # Can pass --config flag to change golangci-lint behavior and to specify config file.
          golangci_lint_flags: "--config=.golangci.yml"
          fail_level: "error"
          reporter: "github-pr-review"
